[package]
name = "lh-gui"
description = "Little Helper desktop application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "little-helper"
path = "src/main.rs"

[dependencies]
lh-core.workspace = true
iced.workspace = true
rfd.workspace = true
crossbeam-channel.workspace = true
hex.workspace = true
