//! Tests against the fixture corpus in `tests/fixtures`, regenerated by
//! `scripts/gen-fixtures.py`. The FLAC files and `reference.ffp` come from the reference
//! `flac`/`metaflac` tools, so those tools — not our own output — are the oracle.
//!
//! `reference.st5` is the same arrangement for shntool, via `scripts/gen-st5-oracle.py`.
//! It matters more than it looks: `.st5` has no specification at all, only shntool's
//! behaviour, so until this file existed both halves of our implementation — the digest and
//! the line layout — were assumptions.

use lh_core::analysis::{Sbe, Verification, sbe, verify};
use lh_core::checksum::{ChecksumFile, ChecksumKind, ffp, st5};
use lh_core::format;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// The FFP the reference tools produced, keyed by file name.
fn reference_ffp() -> HashMap<String, [u8; 16]> {
    let path = fixture("reference.ffp");
    ChecksumFile::read(ChecksumKind::Ffp, &path)
        .expect("reference.ffp should parse")
        .entries
        .into_iter()
        .map(|e| (e.file_name, e.digest))
        .collect()
}

#[test]
fn ffp_matches_the_reference_tools() {
    let reference = reference_ffp();
    assert!(!reference.is_empty(), "reference.ffp is empty");
    for (name, expected) in reference {
        let ours = ffp(&fixture(&name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(
            hex::encode(ours),
            hex::encode(expected),
            "{name}: our FFP disagrees with metaflac"
        );
    }
}

/// ST5 is computed by decoding; FFP is read from the header. They must agree, which is
/// what makes ST5 an independent check rather than a restatement of the stored value.
/// Real shntool 3.0.4 — the build Trader's Little Helper bundles — on the corpus. This is
/// the oracle for the digest *and* for the line layout, and it caught both: we were writing
/// md5sum-style lines into a file whose only reader splits on shntool's `[shntool]` tag.
#[test]
fn st5_matches_real_shntool_digest_and_layout() {
    let path = fixture("reference.st5");
    let reference = ChecksumFile::read(ChecksumKind::St5, &path).expect("reference.st5 parses");
    assert!(!reference.entries.is_empty(), "reference.st5 is empty");

    let mut ours = ChecksumFile::new(ChecksumKind::St5);
    for entry in &reference.entries {
        let digest =
            st5(&fixture(&entry.file_name)).unwrap_or_else(|e| panic!("{}: {e}", entry.file_name));
        assert_eq!(
            hex::encode(digest),
            hex::encode(entry.digest),
            "{}: our ST5 disagrees with shntool",
            entry.file_name
        );
        ours.entries.push(lh_core::checksum::Entry {
            file_name: entry.file_name.clone(),
            digest,
        });
    }

    // And the file we would write is the file shntool wrote, byte for byte. The generator
    // normalises shntool's CRLF to LF and nothing else, so this compares layout, order and
    // digests at once.
    assert_eq!(
        ours.render(),
        std::fs::read_to_string(&path).unwrap(),
        "our .st5 is not the file shntool produced"
    );
}

#[test]
fn st5_by_decode_equals_ffp_from_header() {
    for name in ["cdda-aligned.flac", "cdda-sbe.flac", "hires-24bit.flac"] {
        let path = fixture(name);
        assert_eq!(
            hex::encode(st5(&path).unwrap()),
            hex::encode(ffp(&path).unwrap()),
            "{name}"
        );
    }
}

/// The property that makes ST5 worth having: it survives the format change.
#[test]
fn st5_survives_flac_to_wav() {
    for (wav, flac) in [
        ("cdda-aligned.wav", "cdda-aligned.flac"),
        ("cdda-sbe.wav", "cdda-sbe.flac"),
        ("hires-24bit.wav", "hires-24bit.flac"),
    ] {
        assert_eq!(
            hex::encode(st5(&fixture(wav)).unwrap()),
            hex::encode(st5(&fixture(flac)).unwrap()),
            "{wav} vs {flac}"
        );
    }
}

#[test]
fn probe_reads_stream_parameters() {
    let f = format::probe(&fixture("cdda-aligned.flac")).unwrap();
    assert_eq!(f.stream_info.sample_rate, 44_100);
    assert_eq!(f.stream_info.channels, 2);
    assert_eq!(f.stream_info.bits_per_sample, 16);
    assert_eq!(f.stream_info.total_frames, Some(588 * 10));
    assert!(f.stream_info.is_cdda());

    let m = format::probe(&fixture("mono-48k.wav")).unwrap();
    assert_eq!(m.stream_info.sample_rate, 48_000);
    assert_eq!(m.stream_info.channels, 1);
    assert_eq!(m.stream_info.total_frames, Some(4800));
    assert!(!m.stream_info.is_cdda());
}

/// Principle 2: the vendor string is the provenance record, so we must actually surface it.
#[test]
fn flac_files_report_their_encoder() {
    let f = format::probe(&fixture("cdda-aligned.flac")).unwrap();
    let encoder = f.encoder.expect("reference flac writes a vendor string");
    assert!(
        encoder.starts_with("reference libFLAC"),
        "unexpected vendor string: {encoder:?}"
    );
}

#[test]
fn wav_parser_skips_unknown_chunks() {
    let plain = format::probe(&fixture("cdda-aligned.wav")).unwrap();
    let with_list = format::probe(&fixture("cdda-listchunk.wav")).unwrap();
    assert_eq!(plain.stream_info, with_list.stream_info);
    assert_eq!(
        st5(&fixture("cdda-aligned.wav")).unwrap(),
        st5(&fixture("cdda-listchunk.wav")).unwrap(),
        "a LIST chunk must not change the audio hash"
    );
}

#[test]
fn sbe_detects_a_short_final_sector() {
    let aligned = format::probe(&fixture("cdda-aligned.flac")).unwrap();
    assert_eq!(sbe(&aligned.stream_info), Sbe::Aligned);

    let short = format::probe(&fixture("cdda-sbe.flac")).unwrap();
    assert_eq!(
        sbe(&short.stream_info),
        Sbe::Misaligned {
            remainder_frames: 137
        }
    );

    let hires = format::probe(&fixture("hires-24bit.flac")).unwrap();
    assert!(matches!(sbe(&hires.stream_info), Sbe::NotApplicable { .. }));
}

#[test]
fn verify_passes_a_good_file() {
    assert_eq!(
        verify(&fixture("cdda-aligned.flac")).unwrap(),
        Verification::Ok
    );
}

/// Decodes cleanly but the stored hash is wrong — a content problem.
#[test]
fn verify_reports_a_tampered_md5() {
    match verify(&fixture("wrong-md5.flac")).unwrap() {
        Verification::Md5Mismatch { stored, computed } => assert_ne!(stored, computed),
        other => panic!("expected a mismatch, got {other:?}"),
    }
}

/// Fails to decode — a broken file, which must not be reported as a hash mismatch.
#[test]
fn verify_errors_on_a_truncated_file() {
    assert!(
        verify(&fixture("truncated.flac")).is_err(),
        "a truncated file must surface as an error, not a comparison result"
    );
}

/// Principle 5: name the format and the tool it needs.
#[test]
fn unsupported_formats_say_what_they_need() {
    let err = format::probe(Path::new("show/d1t01.shn")).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("SHN"), "{msg}");
    assert!(msg.contains("shntool"), "{msg}");
}
